# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_auto_20161221_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='nome',
        ),
        migrations.AddField(
            model_name='video',
            name='id_usuario',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='collection_app.Usuario'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
