# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_video_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('fr', 'Forró'), ('rc', 'Rock'), ('pp', 'Pop'), ('sw', 'Swingueira')], default='rc', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
