# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_auto_20161222_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categoria',
            field=models.CharField(choices=[('Forró', 'Forró'), ('Rock', 'Rock'), ('Pop', 'Pop'), ('Swingueira', 'Swingueira')], default='Rock', max_length=30),
        ),
    ]
