# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_auto_20161222_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
